/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module reg1(in, clk, en, out);
  wire _0_;
  input clk;
  input en;
  input in;
  output out;
  sky130_fd_sc_hd__mux2_2 _1_ (
    .A0(out),
    .A1(in),
    .S(en),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(out)
  );
endmodule
