/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module reg4(in, clk, en, out);
  wire [3:0] _0_;
  input clk;
  input en;
  input [3:0] in;
  output [3:0] out;
  sky130_fd_sc_hd__mux2_2 _1_ (
    .A0(out[2]),
    .A1(in[2]),
    .S(en),
    .X(_0_[2])
  );
  sky130_fd_sc_hd__mux2_2 _2_ (
    .A0(out[1]),
    .A1(in[1]),
    .S(en),
    .X(_0_[1])
  );
  sky130_fd_sc_hd__mux2_2 _3_ (
    .A0(out[0]),
    .A1(in[0]),
    .S(en),
    .X(_0_[0])
  );
  sky130_fd_sc_hd__mux2_2 _4_ (
    .A0(out[3]),
    .A1(in[3]),
    .S(en),
    .X(_0_[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _5_ (
    .CLK(clk),
    .D(_0_[0]),
    .Q(out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _6_ (
    .CLK(clk),
    .D(_0_[1]),
    .Q(out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _7_ (
    .CLK(clk),
    .D(_0_[2]),
    .Q(out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _8_ (
    .CLK(clk),
    .D(_0_[3]),
    .Q(out[3])
  );
endmodule
