/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module register(clk, en, D_in, D_out);
  wire _0_;
  input D_in;
  output D_out;
  input clk;
  input en;
  sky130_fd_sc_hd__mux2_2 _1_ (
    .A0(D_out),
    .A1(D_in),
    .S(en),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(D_out)
  );
endmodule
