/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module reg32(in, clk, en, out);
  wire [30:0] _00_;
  input clk;
  input en;
  input [31:0] in;
  output [31:0] out;
  sky130_fd_sc_hd__mux2_2 _01_ (
    .A0(out[29]),
    .A1(in[29]),
    .S(en),
    .X(_00_[29])
  );
  sky130_fd_sc_hd__mux2_2 _02_ (
    .A0(out[28]),
    .A1(in[28]),
    .S(en),
    .X(_00_[28])
  );
  sky130_fd_sc_hd__mux2_2 _03_ (
    .A0(out[27]),
    .A1(in[27]),
    .S(en),
    .X(_00_[27])
  );
  sky130_fd_sc_hd__mux2_2 _04_ (
    .A0(out[26]),
    .A1(in[26]),
    .S(en),
    .X(_00_[26])
  );
  sky130_fd_sc_hd__mux2_2 _05_ (
    .A0(out[25]),
    .A1(in[25]),
    .S(en),
    .X(_00_[25])
  );
  sky130_fd_sc_hd__mux2_2 _06_ (
    .A0(out[24]),
    .A1(in[24]),
    .S(en),
    .X(_00_[24])
  );
  sky130_fd_sc_hd__mux2_2 _07_ (
    .A0(out[23]),
    .A1(in[23]),
    .S(en),
    .X(_00_[23])
  );
  sky130_fd_sc_hd__mux2_2 _08_ (
    .A0(out[22]),
    .A1(in[22]),
    .S(en),
    .X(_00_[22])
  );
  sky130_fd_sc_hd__mux2_2 _09_ (
    .A0(out[21]),
    .A1(in[21]),
    .S(en),
    .X(_00_[21])
  );
  sky130_fd_sc_hd__mux2_2 _10_ (
    .A0(out[20]),
    .A1(in[20]),
    .S(en),
    .X(_00_[20])
  );
  sky130_fd_sc_hd__mux2_2 _11_ (
    .A0(out[19]),
    .A1(in[19]),
    .S(en),
    .X(_00_[19])
  );
  sky130_fd_sc_hd__mux2_2 _12_ (
    .A0(out[18]),
    .A1(in[18]),
    .S(en),
    .X(_00_[18])
  );
  sky130_fd_sc_hd__mux2_2 _13_ (
    .A0(out[17]),
    .A1(in[17]),
    .S(en),
    .X(_00_[17])
  );
  sky130_fd_sc_hd__mux2_2 _14_ (
    .A0(out[16]),
    .A1(in[16]),
    .S(en),
    .X(_00_[16])
  );
  sky130_fd_sc_hd__mux2_2 _15_ (
    .A0(out[15]),
    .A1(in[15]),
    .S(en),
    .X(_00_[15])
  );
  sky130_fd_sc_hd__mux2_2 _16_ (
    .A0(out[14]),
    .A1(in[14]),
    .S(en),
    .X(_00_[14])
  );
  sky130_fd_sc_hd__mux2_2 _17_ (
    .A0(out[13]),
    .A1(in[13]),
    .S(en),
    .X(_00_[13])
  );
  sky130_fd_sc_hd__mux2_2 _18_ (
    .A0(out[12]),
    .A1(in[12]),
    .S(en),
    .X(_00_[12])
  );
  sky130_fd_sc_hd__mux2_2 _19_ (
    .A0(out[11]),
    .A1(in[11]),
    .S(en),
    .X(_00_[11])
  );
  sky130_fd_sc_hd__mux2_2 _20_ (
    .A0(out[10]),
    .A1(in[10]),
    .S(en),
    .X(_00_[10])
  );
  sky130_fd_sc_hd__mux2_2 _21_ (
    .A0(out[9]),
    .A1(in[9]),
    .S(en),
    .X(_00_[9])
  );
  sky130_fd_sc_hd__mux2_2 _22_ (
    .A0(out[8]),
    .A1(in[8]),
    .S(en),
    .X(_00_[8])
  );
  sky130_fd_sc_hd__mux2_2 _23_ (
    .A0(out[7]),
    .A1(in[7]),
    .S(en),
    .X(_00_[7])
  );
  sky130_fd_sc_hd__mux2_2 _24_ (
    .A0(out[6]),
    .A1(in[6]),
    .S(en),
    .X(_00_[6])
  );
  sky130_fd_sc_hd__mux2_2 _25_ (
    .A0(out[5]),
    .A1(in[5]),
    .S(en),
    .X(_00_[5])
  );
  sky130_fd_sc_hd__mux2_2 _26_ (
    .A0(out[4]),
    .A1(in[4]),
    .S(en),
    .X(_00_[4])
  );
  sky130_fd_sc_hd__mux2_2 _27_ (
    .A0(out[3]),
    .A1(in[3]),
    .S(en),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__mux2_2 _28_ (
    .A0(out[2]),
    .A1(in[2]),
    .S(en),
    .X(_00_[2])
  );
  sky130_fd_sc_hd__mux2_2 _29_ (
    .A0(out[1]),
    .A1(in[1]),
    .S(en),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__mux2_2 _30_ (
    .A0(out[0]),
    .A1(in[0]),
    .S(en),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__mux2_2 _31_ (
    .A0(out[30]),
    .A1(in[30]),
    .S(en),
    .X(_00_[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _35_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _36_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(out[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _37_ (
    .CLK(clk),
    .D(_00_[5]),
    .Q(out[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _38_ (
    .CLK(clk),
    .D(_00_[6]),
    .Q(out[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _39_ (
    .CLK(clk),
    .D(_00_[7]),
    .Q(out[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _40_ (
    .CLK(clk),
    .D(_00_[8]),
    .Q(out[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _41_ (
    .CLK(clk),
    .D(_00_[9]),
    .Q(out[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(clk),
    .D(_00_[10]),
    .Q(out[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(clk),
    .D(_00_[11]),
    .Q(out[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(clk),
    .D(_00_[12]),
    .Q(out[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(clk),
    .D(_00_[13]),
    .Q(out[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(clk),
    .D(_00_[14]),
    .Q(out[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clk),
    .D(_00_[15]),
    .Q(out[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(clk),
    .D(_00_[16]),
    .Q(out[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(_00_[17]),
    .Q(out[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clk),
    .D(_00_[18]),
    .Q(out[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_00_[19]),
    .Q(out[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clk),
    .D(_00_[20]),
    .Q(out[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clk),
    .D(_00_[21]),
    .Q(out[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_00_[22]),
    .Q(out[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_00_[23]),
    .Q(out[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_00_[24]),
    .Q(out[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_00_[25]),
    .Q(out[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _58_ (
    .CLK(clk),
    .D(_00_[26]),
    .Q(out[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _59_ (
    .CLK(clk),
    .D(_00_[27]),
    .Q(out[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _60_ (
    .CLK(clk),
    .D(_00_[28]),
    .Q(out[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _61_ (
    .CLK(clk),
    .D(_00_[29]),
    .Q(out[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _62_ (
    .CLK(clk),
    .D(_00_[30]),
    .Q(out[30])
  );
  assign out[31] = 1'bx;
endmodule
